### ISSUE TITLE
Recursion Error when making queries to the database

### ISSUE THREAD

**Issue by jsonfm** [DIGOAI/chatbot-backend#43]
This part generates RecursionError: 

https://github.com/DIGOAI/chatbot-backend/blob/85066d231cf0d8d628f2107d4d987ecaa74f6d8b/src/db/models/ticket.py#L54-L55

**Comment by Scoowy** [comment]
EL problema no era relacionado con la _magic function_ `__repr__` de Python, sino más bien un fallo por parte mía en la escritura de la clase `Ticket` que ereda de `BaseModel` de **Pydantic**.
